
export const TRANSLATIONS = {
  vi: {
    app_name: "Thumbnail AI",
    professional_tool: "Công cụ tạo Thumbnail Chuyên nghiệp",
    setup_api_key: "Cài đặt API Key",
    api_key_desc: "Để sử dụng model Gemini Banana (Image), bạn cần có Google GenAI API key hợp lệ.",
    select_google: "Chọn qua Google",
    enter_manual: "Hoặc nhập API Key thủ công",
    check: "Kiểm tra",
    start_app: "Bắt đầu",
    get_key_link: "Lấy API Key tại đây",
    main_title: "Tạo Thumbnail YouTube",
    auto: "Tự Động",
    main_desc: "Tạo thumbnail thu hút click chỉ trong vài giây. Giữ nguyên khuôn mặt, tự động sắp xếp bố cục và chèn chữ thông minh.",
    config_title: "Cấu hình Thumbnail",
    main_text_label: "Nội dung chính (Main Text)",
    sub_text_label: "Dòng phụ (Sub Text)",
    prompt_label: "Mô tả hình ảnh (Image Prompt)",
    ratio_label: "Tỷ lệ (Ratio)",
    style_label: "Phong cách (Style)",
    generate_btn: "Tạo Thumbnail",
    generating: "Đang tạo...",
    result_preview: "Kết quả (Preview)",
    download: "Tải xuống",
    history_title: "Lịch sử tạo (Recent)",
    clear_all: "Xóa tất cả",
    upload_label: "Hình ảnh tham khảo (Reference Images)",
    upload_desc: "Tải lên ảnh nhân vật để giữ khuôn mặt đồng nhất (Face Consistency).",
    footer_text: "Powered by Tandev.foto",
    placeholder_main: "VD: TẠO ẢNH AI...",
    placeholder_sub: "VD: Bí kíp nghìn đô...",
    placeholder_prompt: "Mô tả chi tiết cảnh bạn muốn tạo...",
    waiting_image: "Ảnh thumbnail sẽ xuất hiện ở đây",
    processing: "Đang xử lý yêu cầu...",
    model_label: "Model",
    valid_key: "Key hợp lệ!",
    invalid_key: "Key không hợp lệ hoặc lỗi kết nối.",
    settings_language: "Ngôn ngữ",
    settings_theme: "Giao diện",
    theme_dark: "Tối",
    theme_light: "Sáng",
    or_enter_manual: "Hoặc nhập API Key thủ công",
    recommended_cloud: "Khuyên dùng cho Google Cloud Projects"
  },
  en: {
    app_name: "Thumbnail AI",
    professional_tool: "Professional Thumbnail Generator",
    setup_api_key: "Setup API Key",
    api_key_desc: "To use Gemini Banana (Image) models, you need a valid Google GenAI API key.",
    select_google: "Select via Google",
    enter_manual: "Or enter API Key manually",
    check: "Check",
    start_app: "Start App",
    get_key_link: "Get an API Key here",
    main_title: "YouTube Thumbnail Generator",
    auto: "Auto",
    main_desc: "Create click-worthy thumbnails in seconds. Maintain face consistency, auto-layout, and smart text insertion.",
    config_title: "Thumbnail Configuration",
    main_text_label: "Main Text",
    sub_text_label: "Sub Text",
    prompt_label: "Image Prompt",
    ratio_label: "Aspect Ratio",
    style_label: "Style",
    generate_btn: "Generate Thumbnail",
    generating: "Generating...",
    result_preview: "Result (Preview)",
    download: "Download",
    history_title: "History (Recent)",
    clear_all: "Clear All",
    upload_label: "Reference Images",
    upload_desc: "Upload character images for Face Consistency.",
    footer_text: "Powered by Tandev.foto",
    placeholder_main: "Ex: AI IMAGE GEN...",
    placeholder_sub: "Ex: $1000 Secret...",
    placeholder_prompt: "Describe the scene you want...",
    waiting_image: "Thumbnail will appear here",
    processing: "Processing request...",
    model_label: "Model",
    valid_key: "Valid Key!",
    invalid_key: "Invalid Key or connection error.",
    settings_language: "Language",
    settings_theme: "Theme",
    theme_dark: "Dark",
    theme_light: "Light",
    or_enter_manual: "Or enter API Key manually",
    recommended_cloud: "Recommended for Google Cloud Projects"
  }
};
